### PR TITLE
Cache user when fetching

### PR DESCRIPTION
**Pull request by Rapougnac**
# Description
Fix `accentColor` parsing on `IUser`s.
This PR also caches users when fetching them from the api.

## Connected issues & other potential problems
-/-
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my changes haven't lowered code coverage

### CODE REVIEW

**Review by l7ssha — APPROVED** [review]

**Comment by Rapougnac** [comment]
Hmm, there's something weird

**Comment by Rapougnac** [comment]
For no reason, sometimes `accent_color` is a string.
But sometimes an int...

**Comment by Rapougnac** [comment]
> For no reason, sometimes `accent_color` is a string.
Seems it was form my side

**Comment by l7ssha** [comment]
@Rapougnac Please solve conflicts and will be good to merge

**Review by l7ssha — APPROVED** [review]

**Pull request merged**
