### PR TITLE
feature: Implement @silent messages

### LINKED ISSUE #439: Implement @silent messages
Ref: https://github.com/discord/discord-api-docs/pull/5910

### PR DESCRIPTION
**Pull request by l7ssha**
# Description

Implement @silent messages

## Connected issues & other potential problems

Fixes #439

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my changes haven't lowered code coverage

### CODE REVIEW

**Review by abitofevrything — APPROVED** [review]
Do we really need to deprecate suppressEmbeds?

**Comment by l7ssha** [comment]
> Do we really need to deprecate suppressEmbeds?

It's just edit message with single flags parameters. Since you can do that using edit message there is no point in having that method

**Comment by NDSo** [comment]
`suppressEmbeds` is an edit allowed against other users' messages. Just make sure that use case is supported through `editMessage` before removing it.

```
  Future<IMessage> editMessage(Snowflake channelId, Snowflake messageId, MessageBuilder builder) async {
    if (!builder.canBeUsedAsNewMessage()) {
      return Future.error(ArgumentError("Cannot edit a message to have neither content nor embeds"));
    }
```

**Comment by l7ssha** [comment]
> `suppressEmbeds` is an edit allowed against other users' messages. Just make sure that use case is supported through `editMessage` before removing it.

ah yes, then it doesnt make sense to remove it. Gonna remove deprecation before merge

**Pull request merged**
